"""Stay time was renamed to Exit time

Revision ID: 3732f2e21dda
Revises: ad50f6189247
Create Date: 2023-04-22 23:43:09.982099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3732f2e21dda'
down_revision = 'ad50f6189247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exit_time', sa.Time(), nullable=False))
        batch_op.drop_column('stay_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stay_time', sa.TIME(), nullable=False))
        batch_op.drop_column('exit_time')

    # ### end Alembic commands ###
