"""Min_stay and Max_stay has been deleted from the Guest table. Now it just stay_time

Revision ID: ad50f6189247
Revises: 68c72042ed46
Create Date: 2023-04-20 23:03:29.235540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad50f6189247'
down_revision = '68c72042ed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stay_time', sa.Time(), nullable=False))
        batch_op.drop_column('max_stay')
        batch_op.drop_column('min_stay')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_stay', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('max_stay', sa.TIME(), nullable=False))
        batch_op.drop_column('stay_time')

    # ### end Alembic commands ###
