"""GuestType name becomes unique

Revision ID: d3b166f8d2e9
Revises: 
Create Date: 2023-04-20 17:48:46.671567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b166f8d2e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_type', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_name', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_type', schema=None) as batch_op:
        batch_op.drop_constraint('uq_name', type_='unique')

    # ### end Alembic commands ###
